version: "3.9"

services:
  nesco-bot-dev:
    image: node:20-alpine
    container_name: nesco-meter-bot-dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      METER_NUMBER: ${METER_NUMBER}
    command: sh -c "yarn install && yarn dev"