version: "3.9"

services:
  nesco-bot:
    build: .
    container_name: nesco-meter-bot
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      METER_NUMBER: ${METER_NUMBER}
      CHROME_PATH: /usr/bin/chromium-browser
    restart: always